import { Project, Subtask, CalendarEvent, UserSettings, FlashcardDeck, Flashcard, MindMap } from '../types';

export const STORAGE_KEYS = {
  INITIALIZED: 'focusflow_defaults_initialized',
  PROJECTS: 'focusflow_projects',
  SUBTASKS: 'focusflow_subtasks',
  TASKS: 'focusflow_tasks', // legado
  CALENDAR: 'focusflow_calendar_events',
  SESSIONS: 'focusflow_sessions',
  SETTINGS: 'focusflow_settings',
  SCRATCHPAD: 'focusflow_scratchpad',
  QUICK_NOTES: 'focusflow_quick_notes',
  MANTRAS: 'focusflow_mantras',
  FLASHCARD_DECKS: 'focusflow_flashcard_decks',
  FLASHCARDS: 'focusflow_flashcards',
  MIND_MAPS: 'focusflow_mind_maps',
};

export const DEFAULT_SETTINGS: UserSettings = {
  pomodoro_time: 25,
  short_break_time: 5,
  long_break_time: 15,
  long_break_interval: 4,
  theme: 'ruby',
  color_mode: 'dark',
  dark_mode_running: true,
  alarm_sound: 'crystal',
  ambient_sound: 'none',
  sound_volume: 0.8,
  ambient_volume: 0.5,
  auto_start_breaks: false,
  auto_start_pomodoros: false,
  strict_focus_mode: false,
};

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: 'FocusFlow: Plataforma & Engenharia',
    description: 'Desenvolvimento do ecossistema moderno com timer, projetos, subtasks e calendário.',
    start_date: '2026-09-01',
    end_date: '2026-10-31',
    color: '#ff2a5f',
    icon: '🚀',
    total_elapsed_seconds: 5400, // 1h 30m
    created_at: new Date().toISOString(),
  },
  {
    id: 'proj-2',
    title: 'Inteligência Artificial & Agentes Autônomos',
    description: 'Estudos aprofundados de RAG multimodal, embeddings e fluxos agentic.',
    start_date: '2026-09-10',
    end_date: '2026-11-30',
    color: '#0ea5e9',
    icon: '🤖',
    total_elapsed_seconds: 3600, // 1h
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_SUBTASKS: Subtask[] = [
  {
    id: 'sub-1',
    project_id: 'proj-1',
    title: 'Arquitetura de Projetos e Time-Tracking por Subtask',
    discipline: 'Engenharia de Software',
    priority: 'alta',
    pomodoros_estimated: 4,
    pomodoros_completed: 2,
    elapsed_seconds: 3000,
    is_completed: false,
    notes: '# Planejamento da Arquitetura\n\n- [x] Modelagem de interfaces no TypeScript\n- [x] Rastreamento preciso de tempo em segundos\n- [ ] Conectar cronômetro ao tempo acumulado\n\n> 💡 *Dica:* Cada subtask acumula tempo individualmente e alimenta o total do projeto.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sub-2',
    project_id: 'proj-1',
    title: 'Editor de Anotações estilo Notion com Markdown',
    discipline: 'Frontend UX',
    priority: 'alta',
    pomodoros_estimated: 3,
    pomodoros_completed: 1,
    elapsed_seconds: 2400,
    is_completed: false,
    notes: '# Requisitos do Editor Notion-style\n\n- Tipografia refinada (JetBrains Mono & Outfit)\n- Checklists interativos clicáveis\n- Callouts com emoji e destaque visual',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sub-3',
    project_id: 'proj-2',
    title: 'Implementação de RAG com Embeddings e Vector Store',
    discipline: 'Inteligência Artificial',
    priority: 'media',
    pomodoros_estimated: 5,
    pomodoros_completed: 2,
    elapsed_seconds: 3600,
    is_completed: false,
    notes: '# Pipeline de Recuperação\n\n1. Chunking contextual de documentos\n2. Indexação vetorial em alta dimensão\n3. Re-ranking semântico',
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'cal-1',
    title: 'Foco: Arquitetura FocusFlow',
    description: 'Desenvolvimento das novas abas de projetos e time-blocking',
    start_time: `${new Date().toISOString().split('T')[0]}T09:00`,
    end_time: `${new Date().toISOString().split('T')[0]}T10:30`,
    project_id: 'proj-1',
    subtask_id: 'sub-1',
    color: '#ff2a5f',
    is_completed: false,
  },
  {
    id: 'cal-2',
    title: 'Estudo: RAG & Vetores Semânticos',
    description: 'Leitura técnica e implementação de embeddings',
    start_time: `${new Date().toISOString().split('T')[0]}T14:00`,
    end_time: `${new Date().toISOString().split('T')[0]}T15:30`,
    project_id: 'proj-2',
    subtask_id: 'sub-3',
    color: '#0ea5e9',
    is_completed: false,
  },
];

// Baralhos de Flashcards Padrão (Sementes Demonstrativas)
export const DEFAULT_FLASHCARD_DECKS: FlashcardDeck[] = [
  {
    id: 'deck-eng-software',
    title: 'Engenharia de Software & Algoritmos',
    description: 'Conceitos avançados de complexidade, design patterns, concorrência e arquitetura distribuída.',
    color: '#0ea5e9',
    icon: '💻',
    project_id: 'proj-1',
    tags: ['Engenharia', 'Algoritmos', 'Clean Code'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'deck-direito-const',
    title: 'Direito Constitucional & Direitos Fundamentais',
    description: 'Garantias fundamentais, remédios constitucionais e cláusulas pétreas para concursos e OAB.',
    color: '#ff2a5f',
    icon: '⚖️',
    tags: ['Concursos', 'OAB', 'Constitucional'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'deck-ingles-tech',
    title: 'Inglês Técnico para Tecnologia & Carreira',
    description: 'Vocabulário essencial para pull requests, system design, documentações e reuniões técnicas.',
    color: '#10b981',
    icon: '🌐',
    tags: ['Inglês', 'Carreira', 'Tech'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

const todayISO = new Date().toISOString().split('T')[0];

// Cartões de Flashcards Padrão (Com SM-2 Inicializado)
export const DEFAULT_FLASHCARDS: Flashcard[] = [
  // Baralho 1: Engenharia de Software
  {
    id: 'card-eng-1',
    deck_id: 'deck-eng-software',
    front: 'Qual é a diferença conceitual entre Concorrência e Paralelismo?',
    back: 'Concorrência é a composição de processos independentes lidando com muitas tarefas (ex: alternância de I/O em um event loop). Paralelismo é a execução simultânea física de cálculos em múltiplos núcleos de CPU ao mesmo tempo.',
    hint: 'Pense em 1 barista alternando pedidos vs 2 baristas trabalhando juntos.',
    tags: ['Sistemas', 'Concorrência'],
    repetition: 0,
    interval_days: 0,
    ease_factor: 2.5,
    due_date: todayISO,
    lapses: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: 'card-eng-2',
    deck_id: 'deck-eng-software',
    front: 'O que diz o Princípio de Substituição de Liskov (LSP) no SOLID?',
    back: 'Objetos de uma superclasse devem poder ser substituídos por objetos de suas subclasses sem quebrar o comportamento ou as expectativas do programa (contratos e invariantes preservados).',
    hint: 'A letra "L" do SOLID. Exemplo clássico: Quadrado não deve herdar de Retângulo se violar suas dimensões.',
    tags: ['SOLID', 'Design Patterns'],
    repetition: 1,
    interval_days: 1,
    ease_factor: 2.5,
    due_date: todayISO,
    lapses: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: 'card-eng-3',
    deck_id: 'deck-eng-software',
    front: 'Em árvores binárias de busca (BST), quais são as complexidades no caso médio e no pior caso?',
    back: 'Caso Médio: O(log n) quando a árvore está equilibrada.\nPior Caso: O(n) quando os elementos foram inseridos em ordem e a árvore degenera em uma lista ligada.',
    hint: 'Lembre-se de árvores AVL ou Red-Black para mitigar o pior caso.',
    tags: ['Algoritmos', 'Estruturas de Dados'],
    repetition: 2,
    interval_days: 6,
    ease_factor: 2.5,
    due_date: todayISO,
    lapses: 0,
    created_at: new Date().toISOString(),
  },

  // Baralho 2: Direito Constitucional
  {
    id: 'card-dir-1',
    deck_id: 'deck-direito-const',
    front: 'Qual remédio constitucional é cabível para assegurar o conhecimento de dados pessoais em entidades governamentais?',
    back: 'Habeas Data (art. 5º, LXXII, "a" da CF/88). É uma ação personalíssima e exige prévio pedido e recusa na esfera administrativa (Súmula 2 do STJ).',
    hint: 'Protege a intimidade informativa e retificação de registros.',
    tags: ['Remédios', 'Direito Constitucional'],
    repetition: 0,
    interval_days: 0,
    ease_factor: 2.5,
    due_date: todayISO,
    lapses: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: 'card-dir-2',
    deck_id: 'deck-direito-const',
    front: 'Quais são as 4 cláusulas pétreas expressas no art. 60, § 4º da Constituição Federal?',
    back: '1. Forma federativa de Estado;\n2. Voto direto, secreto, universal e periódico;\n3. Separação dos Poderes;\n4. Direitos e garantias individuais.',
    hint: 'Mnemônico comum: FO-VO-SE-DI.',
    tags: ['Cláusulas Pétreas', 'CF/88'],
    repetition: 1,
    interval_days: 2,
    ease_factor: 2.65,
    due_date: todayISO,
    lapses: 0,
    created_at: new Date().toISOString(),
  },

  // Baralho 3: Inglês Técnico
  {
    id: 'card-ing-1',
    deck_id: 'deck-ingles-tech',
    front: 'O que significa "trade-off" em engenharia de software e tomada de decisões?',
    back: 'Uma troca de concessões: abrir mão de uma vantagem ou recurso para obter outro benefício (exemplo: abrir mão de menor latência para obter consistência forte).',
    hint: 'Não existe bala de prata; tudo envolve um equilíbrio.',
    tags: ['Vocabulário', 'Decisões'],
    repetition: 1,
    interval_days: 1,
    ease_factor: 2.5,
    due_date: todayISO,
    lapses: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: 'card-ing-2',
    deck_id: 'deck-ingles-tech',
    front: 'O que significa o termo "idempotent" em requisições de API REST?',
    back: 'Uma operação cuja execução repetida múltiplas vezes produz o mesmo efeito no estado do servidor que uma única chamada (ex: GET, PUT e DELETE são idempotentes; POST normalmente não é).',
    hint: 'Mesmo resultado se você chamar 1 vez ou 100 vezes.',
    tags: ['API', 'HTTP'],
    repetition: 0,
    interval_days: 0,
    ease_factor: 2.5,
    due_date: todayISO,
    lapses: 0,
    created_at: new Date().toISOString(),
  },
];

// Mapas Mentais Padrão
export const DEFAULT_MIND_MAPS: MindMap[] = [
  {
    id: 'map-software-arch',
    title: 'Arquitetura de Software Moderna',
    description: 'Mapa sistêmico com padrões de comunicação, caching, resiliência e observabilidade.',
    project_id: 'proj-1',
    root_node_id: 'node-arch-root',
    nodes: [
      {
        id: 'node-arch-root',
        parent_id: null,
        text: 'Arquitetura de Software',
        color: '#ff2a5f',
        icon: '🏛️',
        notes: 'Princípios estruturais e padrões de engenharia para aplicações escaláveis.',
      },
      // Ramo 1: Comunicação
      {
        id: 'node-arch-comm',
        parent_id: 'node-arch-root',
        text: 'Padrões de Comunicação',
        color: '#0ea5e9',
        icon: '📡',
      },
      {
        id: 'node-arch-comm-rest',
        parent_id: 'node-arch-comm',
        text: 'REST & HTTP/3',
        color: '#0ea5e9',
        notes: 'Padrão síncrono ubíquo baseado em recursos e verbos semânticos.',
      },
      {
        id: 'node-arch-comm-grpc',
        parent_id: 'node-arch-comm',
        text: 'gRPC & Protocol Buffers',
        color: '#0ea5e9',
        notes: 'RPC binário de alta performance ideal para comunicação interna entre microsserviços.',
      },
      {
        id: 'node-arch-comm-events',
        parent_id: 'node-arch-comm',
        text: 'Event-Driven (Kafka/RabbitMQ)',
        color: '#0ea5e9',
        notes: 'Desacoplamento temporal, streaming de eventos e tolerância a picos de carga.',
      },
      // Ramo 2: Resiliência
      {
        id: 'node-arch-resilience',
        parent_id: 'node-arch-root',
        text: 'Resiliência & Tolerância',
        color: '#f59e0b',
        icon: '🛡️',
      },
      {
        id: 'node-arch-res-cb',
        parent_id: 'node-arch-resilience',
        text: 'Circuit Breaker',
        color: '#f59e0b',
        notes: 'Interrompe chamadas a serviços com falha contínua para permitir recuperação e evitar falha em cascata.',
      },
      {
        id: 'node-arch-res-retry',
        parent_id: 'node-arch-resilience',
        text: 'Exponential Backoff & Jitter',
        color: '#f59e0b',
        notes: 'Retentativas com esperas crescentes e ruído aleatório para evitar sobrecarga simultânea.',
      },
      {
        id: 'node-arch-res-idem',
        parent_id: 'node-arch-resilience',
        text: 'Chaves de Idempotência',
        color: '#f59e0b',
        notes: 'Garante que duplicatas de rede ou retentativas não gerem transações repetidas.',
      },
      // Ramo 3: Armazenamento & Caching
      {
        id: 'node-arch-storage',
        parent_id: 'node-arch-root',
        text: 'Armazenamento & Cache',
        color: '#10b981',
        icon: '💾',
      },
      {
        id: 'node-arch-storage-redis',
        parent_id: 'node-arch-storage',
        text: 'Redis (Cache In-Memory)',
        color: '#10b981',
        notes: 'Cache distribuído com TTL, estruturas de dados ricas e pub/sub.',
      },
      {
        id: 'node-arch-storage-pg',
        parent_id: 'node-arch-storage',
        text: 'PostgreSQL & Índices B-Tree/GIN',
        color: '#10b981',
        notes: 'Banco relacional ACID robusto com suporte a JSONB e extensões vetoriais (pgvector).',
      },
      // Ramo 4: Observabilidade
      {
        id: 'node-arch-obs',
        parent_id: 'node-arch-root',
        text: 'Observabilidade Total',
        color: '#8b5cf6',
        icon: '📊',
      },
      {
        id: 'node-arch-obs-metrics',
        parent_id: 'node-arch-obs',
        text: 'Métricas (Prometheus/Grafana)',
        color: '#8b5cf6',
        notes: 'Taxa de requisições, erros e durações (Métricas RED/USE).',
      },
      {
        id: 'node-arch-obs-traces',
        parent_id: 'node-arch-obs',
        text: 'Tracing (OpenTelemetry)',
        color: '#8b5cf6',
        notes: 'Rastreamento ponta a ponta do fluxo de requisições entre serviços.',
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
